#import "components.typ": *

#let block-open(
  transfer: none,
  input: none,
  output: none,
  width: 2,
  height: 2em,
  line: -2,
  start: 1,
  spacing: (1.5em, 1.5em),
  node-stroke: 1pt,
  mark-scale: 80%,
  node-maker: rnode,
  edge-maker: arrow,
) = control-diagram(
  spacing: spacing,
  node-stroke: node-stroke,
  mark-scale: mark-scale,
  let (O1, O2, O3) = (
    (start, line),
    (start + width, line),
    (start + 2 * width, line),
  ),
  node-maker(O2, transfer, height: height),
  edge-maker(O1, O2, input),
  edge-maker(O2, O3, output),
)

#let block-closed(
  transfer: none,
  transfer2: none,
  input: none,
  output: none,
  output2: none,
  loss: none,
  reference: none,
  line: 0.5,
  start: 1,
  reference-gap: auto,
  input-gap: auto,
  feedback-height: 1.25,
  label-size: 0.6em,
  spacing: (1.5em, 1.5em),
  node-stroke: 1pt,
  mark-scale: 80%,
  node-maker: rnode,
  ref-maker: reference,
  edge-maker: arrow,
  feedback-edge-maker: uturn-v,
) = control-diagram(
  spacing: spacing,
  node-stroke: node-stroke,
  mark-scale: mark-scale,
  let dist-rl = if reference-gap == auto {
    auto-gap(reference, scale: 0.8)
  } else {
    reference-gap
  },
  let dist-lc = if input-gap == auto {
    auto-gap(input, scale: 1.4)
  } else {
    input-gap
  },
  let (R, L, C) = (
    (start, line),
    (start + dist-rl, line),
    (start + dist-lc, line),
  ),
  let H = (start + dist-lc, line + feedback-height),
  ref-maker(
    L,
    loss: loss,
    loss-offset: (1.5 - dist-rl, -0.75),
    plus-offset: (1.1 - dist-rl, -0.25),
    minus-offset: (1.3 - dist-rl, 0.35),
  ),
  node-maker(C, transfer),
  node-maker(H, transfer2),
  edge-maker(R, L, edge-label(reference, size: label-size)),
  edge-maker(L, C, edge-label(input, size: label-size)),
  feedback-edge-maker(C, H, edge-label(output, size: label-size), height: feedback-height),
  edge-maker(H, L, edge-label(output2, size: label-size), label-pos: 0.25, corner: right),
)

#let sys-open(
  controler: none,
  actuator: none,
  process: none,
  input: none,
  output: none,
  output2: none,
  output3: none,
  subunit: none,
  line: -2,
  start: -2,
  spacing: (1.5em, 1.5em),
  node-stroke: 1pt,
  mark-scale: 80%,
  node-maker: rnode,
  edge-maker: arrow,
  boundary-edge-maker: uturn,
  label-maker: label,
) = control-diagram(
  spacing: spacing,
  node-stroke: node-stroke,
  mark-scale: mark-scale,
  let (O1, C, A, P, O2) = (
    (start, line),
    (start + 3, line),
    (start + 7, line),
    (start + 10, line),
    (start + 13, line),
  ),
  let (B1, B2, M) = (
    (start + 5, line),
    (start + 11.5, line),
    (start + 8.5, line + 0.85),
  ),
  node-maker(C, controler),
  node-maker(A, actuator),
  node-maker(P, process),
  edge-maker(O1, C, input),
  edge-maker(C, A, output),
  edge-maker(A, P, output2),
  edge-maker(P, O2, output3),
  boundary-edge-maker(B1, B2, none, marks: "--", corner: left),
  label-maker(M, subunit),
)

#let sys-closed(
  controler: none,
  actuator: none,
  sensor: none,
  input: none,
  output: none,
  output2: none,
  loss: none,
  reference: none,
  line: 0.5,
  start: 1,
  feedback-height: 1.25,
  spacing: (1.5em, 1.5em),
  node-stroke: 1pt,
  mark-scale: 80%,
  node-maker: rnode,
  ref-maker: reference,
  edge-maker: arrow,
) = control-diagram(
  spacing: spacing,
  node-stroke: node-stroke,
  mark-scale: mark-scale,
  let (R, O, T, A) = (
    (start, line),
    (start + 2, line),
    (start + 4.5, line),
    (start + 8, line),
  ),
  let S = (start + 4.5, line + feedback-height),
  node-maker(R, reference),
  ref-maker(
    O,
    loss: loss,
    loss-offset: (0, -0.75),
    plus-offset: (-0.4, 0),
    minus-offset: (-0.2, 0.35),
  ),
  node-maker(T, controler),
  node-maker(S, sensor),
  node-maker(A, actuator),
  edge-maker(R, O, none),
  edge-maker(O, T, input),
  edge-maker(T, A, output),
  edge-maker(A, S, none, corner: right),
  edge-maker(S, O, output2, label-pos: 0.6, corner: right),
)
