[package]
    name = "consketcher"
    version = "0.1.0"
    entrypoint = "src/lib.typ"
    authors = ["ivaquero"]
    license = "MIT"
    description = "Draws control blocks using CeTZ"
    repository = "https://github.com/ivaquero/typst-consketcher"
